# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efa30bc54ea0d2b9e7412ab0508692d6506674ab9b53feff66ab684a6fade28b649d226d7dd67128f029fb8bfb88a8786e7b078fa4585a3793a98e86df398567

test:
  secret_key_base: ba89991ca6ffbc0fa73e5836d7d5abb10e315a1001f037953907ddf108cd512079680f9dce71e38d039bb97649bcb977c51f75c4f5133d9b7d0716af757f2a40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
